/// Catálogo de las 61 variantes de tema del cliente desktop (33 oscuras + 28
/// claras), con la paleta resuelta de cada una.
///
/// Port de `openher-flutter-desktop/lib/ui/core/theme_variants.dart`, que a su
/// vez es port de `web/src/context/themeVariant.tsx` y de los JSON de
/// `web/public/themes/`. Los 61 ids, los nombres y los 16 slots de cada
/// variante son los del escritorio sin renombrar nada: la elección de tema es
/// la misma clave en las dos apps, así que un id no se traduce ni se reordena
/// de otra manera.
///
/// ## Dónde está el `ThemeData`
/// No acá. Este archivo es del mismo tipo que `tokens.dart` — datos puros, sin
/// `BuildContext` ni `Theme` — y el `ThemeData` lo arma `AppTheme.variantOf` en
/// `theme.dart`. Que haya un solo constructor de temas es lo que garantiza que
/// un tema con variante y `AppTheme.light()` compartan exactamente la misma
/// estructura (barras, hojas, tarjetas, tipografía) y no se diferencien más que
/// en la paleta.
///
/// ## Qué es literal y qué no
/// - **Literal**: la paleta de cada variante. No sale de los tokens y no
///   podría salir: `tokens.dart` es el chrome **monocromo** de la casa (gris;
///   el color real vive en el scope de diffs) y "Dracula" o "Gruvbox" son, por
///   definición, paletas ajenas. Estos 16 valores por tema son el dato, igual
///   que en el escritorio, donde tampoco se derivaron de los tokens sino del
///   `resolveTheme` de la web.
/// - **Derivado, nunca hardcodeado**: [ThemeVariantColors.surfaceHover] (la
///   mezcla de `surface-strong`/`border-strong` que produce `--surface-hover` en
///   el CSS) y [ThemeVariantColors.onColor] (el legible que va encima de un
///   acento). Se calculan igual que en el escritorio para que dos temas no
///   puedan divergir por una constante repetida.
/// - **De los tokens**: la estructura. Radios, espaciado, escala tipográfica,
///   alto de barras, radio de hoja y scrim salen de `tokens.dart` para todos los
///   temas, monocromo incluido, así que elegir una variante cambia los colores
///   y no el layout.
///
/// ## Lo que el port no trae, y por qué
/// - `customDefaults`, `toJson`/`fromJson` e `isCustom`: son el `ThemeCreator`
///   de la web, que crea paletas guardadas por el usuario. Acá no se crean
///   temas — Ajustes sólo elige un id de este catálogo — y lo que se persiste
///   es el id, no la paleta; serializarla sería un formato que nadie escribe.
/// - `toColorScheme`: el `ColorScheme` lo arma `AppTheme` una sola vez, para
///   que el camino de la variante y el de los tokens no puedan separarse.
/// - El `FlexThemeData` del escritorio: esta app no depende de
///   `flex_color_scheme` (`pubspec.yaml` no lo trae) y el escritorio lo usaba
///   sólo como `ThemeData` base. Acá la base es `ThemeData.light()/dark()`, la
///   de hoy, así que la variante no arrastra una paleta tonal ajena.
library;

import 'dart:ui' show Brightness, Color;

import 'package:flutter/foundation.dart' show immutable;

/// Tipo de una variante: fija el brillo de su paleta y la sección del selector.
enum ThemeVariantKind {
  light,
  dark;

  /// Valor serializable (id persistido en las prefs).
  String get wire => name;

  /// Brillo Material de la paleta.
  Brightness get brightness =>
      this == ThemeVariantKind.dark ? Brightness.dark : Brightness.light;

  /// Etiqueta humana para la UI (sin emojis).
  String get label => this == ThemeVariantKind.dark ? 'Oscuro' : 'Claro';

  /// Tolera `null` y basura: un tipo desconocido es `dark`, no un crash.
  static ThemeVariantKind fromWire(String? raw) =>
      raw == 'light' ? ThemeVariantKind.light : ThemeVariantKind.dark;
}

/// Paleta resuelta de una variante.
///
/// Los 16 slots son los que existen en el CSS del cliente desktop
/// (`--bg`, `--surface`, `--surface-strong`, `--border`, `--border-strong`,
/// `--text`, `--muted`, `--primary`, `--accent`, `--secondary`, `--danger`,
/// `--warning`, `--success`, `--info`, `--surface-strong` del código y
/// `--code-text`).
@immutable
class ThemeVariantColors {
  const ThemeVariantColors({
    required this.bg,
    required this.surface,
    required this.surfaceStrong,
    required this.border,
    required this.borderStrong,
    required this.text,
    required this.muted,
    required this.primary,
    required this.accent,
    required this.secondary,
    required this.danger,
    required this.warning,
    required this.success,
    required this.info,
    required this.codeBg,
    required this.codeText,
  });

  /// Fondo raíz de la app (`--bg`).
  final Color bg;

  /// Superficie base de paneles (`--surface`).
  final Color surface;

  /// Superficie fuerte: elementos, inputs, código (`--surface-strong`).
  final Color surfaceStrong;

  /// Borde base (`--border`).
  final Color border;

  /// Borde activo/fuerte (`--border-strong`).
  final Color borderStrong;

  /// Texto principal (`--text`).
  final Color text;

  /// Texto atenuado (`--muted`).
  final Color muted;

  /// Acento primario (`--primary`).
  final Color primary;

  /// Acento secundario (`--accent`).
  final Color accent;

  /// Secundario (`--secondary`).
  final Color secondary;

  /// Semántico de error (`--danger`). Con variante, el chrome deja de ser
  /// monocromo y éste es el `error` real del `ColorScheme` (el tema
  /// monocromo mantiene el gris del token `danger`).
  final Color danger;

  /// Semántico de aviso (`--warning`).
  final Color warning;

  /// Semántico de éxito (`--success`).
  final Color success;

  /// Semántico informativo (`--info`).
  final Color info;

  /// Fondo de bloques de código (`--surface-strong` del scope de código).
  final Color codeBg;

  /// Texto de código (`--code-text`).
  final Color codeText;

  /// Hover derivado: la misma mezcla que el `--surface-hover` de `tokens.css`.
  Color get surfaceHover =>
      Color.lerp(surfaceStrong, borderStrong, 0.5) ?? surfaceStrong;

  /// Texto legible sobre [color] (el de mayor contraste, blanco o negro).
  ///
  /// Se usa para `onPrimary`/`onSecondary`/`onError`: una paleta con acento
  /// claro necesita texto oscuro y una con acento oscuro necesita texto
  /// claro, y ningún token puede saber de antemano cuál de los dos.
  static Color onColor(Color color) {
    final luminance = color.computeLuminance();
    final whiteContrast = 1.05 / (luminance + 0.05);
    final blackContrast = (luminance + 0.05) / 0.05;
    return blackContrast >= whiteContrast
        ? const Color(0xFF0A0A0A)
        : const Color(0xFFFFFFFF);
  }

  /// Los colores con los que se previsualiza la paleta en el selector: fondo,
  /// marco, acento primario y acento secundario. Mismo criterio que el
  /// `ThemePicker` del escritorio, para que el ojo reconozca la variante.
  List<Color> get swatch => <Color>[bg, surfaceStrong, primary, accent];
}

/// Variante de tema: nombre, tipo y paleta.
@immutable
class ThemeVariant {
  const ThemeVariant({
    required this.id,
    required this.name,
    required this.kind,
    required this.colors,
  });

  /// Id estable (persistido en las prefs; `"<tema>-light"` para las paletas
  /// claras, igual que en el escritorio).
  final String id;

  /// Nombre humano para la UI.
  final String name;

  /// Tipo (brillo de la paleta y sección del selector).
  final ThemeVariantKind kind;

  /// Paleta de la variante.
  final ThemeVariantColors colors;

  /// `'Claro'`/`'Oscuro'`.
  String get kindLabel => kind.label;
}

/// Catálogo de variantes.
abstract final class ThemeVariants {
  /// Las 61 entradas del cliente desktop con sus paletas reales: los 33 temas
  /// del original (oscuros) más las 28 paletas claras que los JSON definían
  /// aparte, para que el selector agrupe por Claro/Oscuro.
  static const List<ThemeVariant> builtIn = <ThemeVariant>[
    ThemeVariant(
      id: 'aura',
      name: "Aura",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF0F0F0F),
        surface: Color(0xFF15141B),
        surfaceStrong: Color(0xFF15141B),
        border: Color(0xFF2D2D2D),
        borderStrong: Color(0xFF6D6D6D),
        text: Color(0xFFEDECEE),
        muted: Color(0xFF7C7C7C),
        primary: Color(0xFFA277FF),
        accent: Color(0xFFA277FF),
        secondary: Color(0xFFF694FF),
        danger: Color(0xFFFF6767),
        warning: Color(0xFFFFCA85),
        success: Color(0xFF61FFCA),
        info: Color(0xFFA277FF),
        codeBg: Color(0xFF15141B),
        codeText: Color(0xFFEDECEE),
      ),
    ),
    ThemeVariant(
      id: 'ayu',
      name: "Ayu",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF0B0E14),
        surface: Color(0xFF0F131A),
        surfaceStrong: Color(0xFF0D1017),
        border: Color(0xFF6C7380),
        borderStrong: Color(0xFF6C7380),
        text: Color(0xFFBFBDB6),
        muted: Color(0xFF787C85),
        primary: Color(0xFF59C2FF),
        accent: Color(0xFFE6B450),
        secondary: Color(0xFFD2A6FF),
        danger: Color(0xFFD95757),
        warning: Color(0xFFE6B673),
        success: Color(0xFF7FD962),
        info: Color(0xFF39BAE6),
        codeBg: Color(0xFF0D1017),
        codeText: Color(0xFFBFBDB6),
      ),
    ),
    ThemeVariant(
      id: 'carbonfox',
      name: "Carbonfox",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF161616),
        surface: Color(0xFF1A1A1A),
        surfaceStrong: Color(0xFF1E1E1E),
        border: Color(0xFF303030),
        borderStrong: Color(0xFF33B1FF),
        text: Color(0xFFF2F4F8),
        muted: Color(0xFF7D848F),
        primary: Color(0xFF33B1FF),
        accent: Color(0xFFFF7EB6),
        secondary: Color(0xFF78A9FF),
        danger: Color(0xFFEE5396),
        warning: Color(0xFFF1C21B),
        success: Color(0xFF25BE6A),
        info: Color(0xFF78A9FF),
        codeBg: Color(0xFF1E1E1E),
        codeText: Color(0xFFA9AFBC),
      ),
    ),
    ThemeVariant(
      id: 'carbonfox-light',
      name: "Carbonfox (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFFFFFF),
        surface: Color(0xFFF4F4F4),
        surfaceStrong: Color(0xFFF4F4F4),
        border: Color(0xFFDCDCDC),
        borderStrong: Color(0xFF0043CE),
        text: Color(0xFF161616),
        muted: Color(0xFF6F6F6F),
        primary: Color(0xFF0043CE),
        accent: Color(0xFF9F1853),
        secondary: Color(0xFF0043CE),
        danger: Color(0xFF9F1853),
        warning: Color(0xFF007D79),
        success: Color(0xFF198038),
        info: Color(0xFF0043CE),
        codeBg: Color(0xFFF4F4F4),
        codeText: Color(0xFF161616),
      ),
    ),
    ThemeVariant(
      id: 'catppuccin',
      name: "Catppuccin",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF1E1E2E),
        surface: Color(0xFF181825),
        surfaceStrong: Color(0xFF11111B),
        border: Color(0xFF313244),
        borderStrong: Color(0xFF45475A),
        text: Color(0xFFCDD6F4),
        muted: Color(0xFF9399B2),
        primary: Color(0xFF89B4FA),
        accent: Color(0xFFF5C2E7),
        secondary: Color(0xFFCBA6F7),
        danger: Color(0xFFF38BA8),
        warning: Color(0xFFF9E2AF),
        success: Color(0xFFA6E3A1),
        info: Color(0xFF94E2D5),
        codeBg: Color(0xFF11111B),
        codeText: Color(0xFFCDD6F4),
      ),
    ),
    ThemeVariant(
      id: 'catppuccin-light',
      name: "Catppuccin (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFEFF1F5),
        surface: Color(0xFFE6E9EF),
        surfaceStrong: Color(0xFFDCE0E8),
        border: Color(0xFFCCD0DA),
        borderStrong: Color(0xFFBCC0CC),
        text: Color(0xFF4C4F69),
        muted: Color(0xFF696C7D),
        primary: Color(0xFF1E66F5),
        accent: Color(0xFFEA76CB),
        secondary: Color(0xFF8839EF),
        danger: Color(0xFFD20F39),
        warning: Color(0xFFBE7919),
        success: Color(0xFF3D9829),
        info: Color(0xFF179299),
        codeBg: Color(0xFFDCE0E8),
        codeText: Color(0xFF4C4F69),
      ),
    ),
    ThemeVariant(
      id: 'catppuccin-frappe',
      name: "Catppuccin Frappé",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF303446),
        surface: Color(0xFF292C3C),
        surfaceStrong: Color(0xFF232634),
        border: Color(0xFF414559),
        borderStrong: Color(0xFF51576D),
        text: Color(0xFFC6D0F5),
        muted: Color(0xFF949CB8),
        primary: Color(0xFF8DA4E2),
        accent: Color(0xFFF4B8E4),
        secondary: Color(0xFFCA9EE6),
        danger: Color(0xFFE78284),
        warning: Color(0xFFE5C890),
        success: Color(0xFFA6D189),
        info: Color(0xFF81C8BE),
        codeBg: Color(0xFF232634),
        codeText: Color(0xFFC6D0F5),
      ),
    ),
    ThemeVariant(
      id: 'catppuccin-macchiato',
      name: "Catppuccin Macchiato",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF24273A),
        surface: Color(0xFF1E2030),
        surfaceStrong: Color(0xFF181926),
        border: Color(0xFF363A4F),
        borderStrong: Color(0xFF494D64),
        text: Color(0xFFCAD3F5),
        muted: Color(0xFF939AB7),
        primary: Color(0xFF8AADF4),
        accent: Color(0xFFF5BDE6),
        secondary: Color(0xFFC6A0F6),
        danger: Color(0xFFED8796),
        warning: Color(0xFFEED49F),
        success: Color(0xFFA6DA95),
        info: Color(0xFF8BD5CA),
        codeBg: Color(0xFF181926),
        codeText: Color(0xFFCAD3F5),
      ),
    ),
    ThemeVariant(
      id: 'cobalt2',
      name: "Cobalt2",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF193549),
        surface: Color(0xFF122738),
        surfaceStrong: Color(0xFF1F4662),
        border: Color(0xFF1F4662),
        borderStrong: Color(0xFF0088FF),
        text: Color(0xFFFFFFFF),
        muted: Color(0xFFADB7C9),
        primary: Color(0xFF0088FF),
        accent: Color(0xFF2AFFDF),
        secondary: Color(0xFF9A5FEB),
        danger: Color(0xFFFF0088),
        warning: Color(0xFFFFC600),
        success: Color(0xFF9EFF80),
        info: Color(0xFFFF9D00),
        codeBg: Color(0xFF1F4662),
        codeText: Color(0xFFFFFFFF),
      ),
    ),
    ThemeVariant(
      id: 'cobalt2-light',
      name: "Cobalt2 (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFFFFFF),
        surface: Color(0xFFF5F7FA),
        surfaceStrong: Color(0xFFE8ECF1),
        border: Color(0xFFD3DAE3),
        borderStrong: Color(0xFF0066CC),
        text: Color(0xFF193549),
        muted: Color(0xFF5C6B7D),
        primary: Color(0xFF0066CC),
        accent: Color(0xFF00ACC1),
        secondary: Color(0xFF7C4DFF),
        danger: Color(0xFFE91E63),
        warning: Color(0xFFCC7A00),
        success: Color(0xFF48A64C),
        info: Color(0xFFFF5722),
        codeBg: Color(0xFFE8ECF1),
        codeText: Color(0xFF193549),
      ),
    ),
    ThemeVariant(
      id: 'cursor',
      name: "Cursor",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF181818),
        surface: Color(0xFF141414),
        surfaceStrong: Color(0xFF262626),
        border: Color(0x13E4E4E4),
        borderStrong: Color(0xFF88C0D0),
        text: Color(0xFFE4E4E4),
        muted: Color(0x5EE4E4E4),
        primary: Color(0xFF88C0D0),
        accent: Color(0xFF88C0D0),
        secondary: Color(0xFF81A1C1),
        danger: Color(0xFFE34671),
        warning: Color(0xFFF1B467),
        success: Color(0xFF3FA266),
        info: Color(0xFF81A1C1),
        codeBg: Color(0xFF262626),
        codeText: Color(0xFFE4E4E4),
      ),
    ),
    ThemeVariant(
      id: 'cursor-light',
      name: "Cursor (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFCFCFC),
        surface: Color(0xFFF3F3F3),
        surfaceStrong: Color(0xFFEDEDED),
        border: Color(0x13141414),
        borderStrong: Color(0xFF6F9BA6),
        text: Color(0xFF141414),
        muted: Color(0xAD141414),
        primary: Color(0xFF69939E),
        accent: Color(0xFF6F9BA6),
        secondary: Color(0xFF3C7CAB),
        danger: Color(0xFFCF2D56),
        warning: Color(0xFFDB704B),
        success: Color(0xFF1F8A65),
        info: Color(0xFF3C7CAB),
        codeBg: Color(0xFFEDEDED),
        codeText: Color(0xFF141414),
      ),
    ),
    ThemeVariant(
      id: 'dracula',
      name: "Dracula",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF282A36),
        surface: Color(0xFF21222C),
        surfaceStrong: Color(0xFF44475A),
        border: Color(0xFF44475A),
        borderStrong: Color(0xFFBD93F9),
        text: Color(0xFFF8F8F2),
        muted: Color(0xFF8995BB),
        primary: Color(0xFFBD93F9),
        accent: Color(0xFF8BE9FD),
        secondary: Color(0xFFFF79C6),
        danger: Color(0xFFFF5555),
        warning: Color(0xFFF1FA8C),
        success: Color(0xFF50FA7B),
        info: Color(0xFFFFB86C),
        codeBg: Color(0xFF44475A),
        codeText: Color(0xFFF8F8F2),
      ),
    ),
    ThemeVariant(
      id: 'dracula-light',
      name: "Dracula (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFF8F8F2),
        surface: Color(0xFFE8E8E2),
        surfaceStrong: Color(0xFFD8D8D2),
        border: Color(0xFFC8C8C2),
        borderStrong: Color(0xFFBD93F9),
        text: Color(0xFF282A36),
        muted: Color(0xFF5D6C9C),
        primary: Color(0xFFA17DD4),
        accent: Color(0xFF8BE9FD),
        secondary: Color(0xFFFF79C6),
        danger: Color(0xFFF25151),
        warning: Color(0xFF858A4D),
        success: Color(0xFF34A350),
        info: Color(0xFFB3814C),
        codeBg: Color(0xFFD8D8D2),
        codeText: Color(0xFF282A36),
      ),
    ),
    ThemeVariant(
      id: 'everforest',
      name: "Everforest",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF2D353B),
        surface: Color(0xFF333C43),
        surfaceStrong: Color(0xFF343F44),
        border: Color(0xFF859289),
        borderStrong: Color(0xFF9DA9A0),
        text: Color(0xFFD3C6AA),
        muted: Color(0xFF9BA39A),
        primary: Color(0xFFA7C080),
        accent: Color(0xFFD699B6),
        secondary: Color(0xFF7FBBB3),
        danger: Color(0xFFE67E80),
        warning: Color(0xFFE69875),
        success: Color(0xFFA7C080),
        info: Color(0xFF83C092),
        codeBg: Color(0xFF343F44),
        codeText: Color(0xFFD3C6AA),
      ),
    ),
    ThemeVariant(
      id: 'everforest-light',
      name: "Everforest (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFDF6E3),
        surface: Color(0xFFEFEBD4),
        surfaceStrong: Color(0xFFF4F0D9),
        border: Color(0xFF939F91),
        borderStrong: Color(0xFF829181),
        text: Color(0xFF5C6A72),
        muted: Color(0xFF6C7268),
        primary: Color(0xFF7F9101),
        accent: Color(0xFFDF69BA),
        secondary: Color(0xFF3A94C5),
        danger: Color(0xFFF85552),
        warning: Color(0xFFDD7122),
        success: Color(0xFF7F9101),
        info: Color(0xFF329F76),
        codeBg: Color(0xFFF4F0D9),
        codeText: Color(0xFF5C6A72),
      ),
    ),
    ThemeVariant(
      id: 'flexoki',
      name: "Flexoki",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF100F0F),
        surface: Color(0xFF1C1B1A),
        surfaceStrong: Color(0xFF282726),
        border: Color(0xFF575653),
        borderStrong: Color(0xFF6F6E69),
        text: Color(0xFFCECDC3),
        muted: Color(0xFF7D7D78),
        primary: Color(0xFFDA702C),
        accent: Color(0xFF8B7EC8),
        secondary: Color(0xFF4385BE),
        danger: Color(0xFFD14D41),
        warning: Color(0xFFDA702C),
        success: Color(0xFF879A39),
        info: Color(0xFF3AA99F),
        codeBg: Color(0xFF282726),
        codeText: Color(0xFFB7B5AC),
      ),
    ),
    ThemeVariant(
      id: 'flexoki-light',
      name: "Flexoki (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFFFCF0),
        surface: Color(0xFFF2F0E5),
        surfaceStrong: Color(0xFFE6E4D9),
        border: Color(0xFFB7B5AC),
        borderStrong: Color(0xFF878580),
        text: Color(0xFF100F0F),
        muted: Color(0xFF6F6E69),
        primary: Color(0xFF205EA6),
        accent: Color(0xFFBC5215),
        secondary: Color(0xFF5E409D),
        danger: Color(0xFFAF3029),
        warning: Color(0xFFBC5215),
        success: Color(0xFF66800B),
        info: Color(0xFF24837B),
        codeBg: Color(0xFFE6E4D9),
        codeText: Color(0xFF64635F),
      ),
    ),
    ThemeVariant(
      id: 'github',
      name: "GitHub",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF0D1117),
        surface: Color(0xFF010409),
        surfaceStrong: Color(0xFF161B22),
        border: Color(0xFF30363D),
        borderStrong: Color(0xFF58A6FF),
        text: Color(0xFFC9D1D9),
        muted: Color(0xFF8B949E),
        primary: Color(0xFF58A6FF),
        accent: Color(0xFF39C5CF),
        secondary: Color(0xFFBC8CFF),
        danger: Color(0xFFF85149),
        warning: Color(0xFFE3B341),
        success: Color(0xFF3FB950),
        info: Color(0xFFD29922),
        codeBg: Color(0xFF161B22),
        codeText: Color(0xFFC9D1D9),
      ),
    ),
    ThemeVariant(
      id: 'github-light',
      name: "GitHub (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFFFFFF),
        surface: Color(0xFFF6F8FA),
        surfaceStrong: Color(0xFFF0F3F6),
        border: Color(0xFFD0D7DE),
        borderStrong: Color(0xFF0969DA),
        text: Color(0xFF24292F),
        muted: Color(0xFF57606A),
        primary: Color(0xFF0969DA),
        accent: Color(0xFF1B7C83),
        secondary: Color(0xFF8250DF),
        danger: Color(0xFFCF222E),
        warning: Color(0xFF9A6700),
        success: Color(0xFF1A7F37),
        info: Color(0xFFBC4C00),
        codeBg: Color(0xFFF0F3F6),
        codeText: Color(0xFF24292F),
      ),
    ),
    ThemeVariant(
      id: 'gruvbox',
      name: "Gruvbox",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF282828),
        surface: Color(0xFF3C3836),
        surfaceStrong: Color(0xFF504945),
        border: Color(0xFF665C54),
        borderStrong: Color(0xFFEBDBB2),
        text: Color(0xFFEBDBB2),
        muted: Color(0xFF9D8F82),
        primary: Color(0xFF83A598),
        accent: Color(0xFF8EC07C),
        secondary: Color(0xFFD3869B),
        danger: Color(0xFFFB4934),
        warning: Color(0xFFFE8019),
        success: Color(0xFFB8BB26),
        info: Color(0xFFFABD2F),
        codeBg: Color(0xFF504945),
        codeText: Color(0xFFEBDBB2),
      ),
    ),
    ThemeVariant(
      id: 'gruvbox-light',
      name: "Gruvbox (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFBF1C7),
        surface: Color(0xFFEBDBB2),
        surfaceStrong: Color(0xFFD5C4A1),
        border: Color(0xFFBDAE93),
        borderStrong: Color(0xFF3C3836),
        text: Color(0xFF3C3836),
        muted: Color(0xFF76695F),
        primary: Color(0xFF076678),
        accent: Color(0xFF427B58),
        secondary: Color(0xFF8F3F71),
        danger: Color(0xFF9D0006),
        warning: Color(0xFFAF3A03),
        success: Color(0xFF79740E),
        info: Color(0xFFB57614),
        codeBg: Color(0xFFD5C4A1),
        codeText: Color(0xFF3C3836),
      ),
    ),
    ThemeVariant(
      id: 'kanagawa',
      name: "Kanagawa",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF1F1F28),
        surface: Color(0xFF2A2A37),
        surfaceStrong: Color(0xFF363646),
        border: Color(0xFF54546D),
        borderStrong: Color(0xFFC38D9D),
        text: Color(0xFFDCD7BA),
        muted: Color(0xFF8E8D87),
        primary: Color(0xFF7E9CD8),
        accent: Color(0xFFD27E99),
        secondary: Color(0xFF957FB8),
        danger: Color(0xFFE82424),
        warning: Color(0xFFD7A657),
        success: Color(0xFF98BB6C),
        info: Color(0xFF76946A),
        codeBg: Color(0xFF363646),
        codeText: Color(0xFFDCD7BA),
      ),
    ),
    ThemeVariant(
      id: 'kanagawa-light',
      name: "Kanagawa (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFF2E9DE),
        surface: Color(0xFFEAE4D7),
        surfaceStrong: Color(0xFFE3DCD2),
        border: Color(0xFFD4CBBF),
        borderStrong: Color(0xFFC38D9D),
        text: Color(0xFF54433A),
        muted: Color(0xFF6F6760),
        primary: Color(0xFF2D4F67),
        accent: Color(0xFFD27E99),
        secondary: Color(0xFF957FB8),
        danger: Color(0xFFE82424),
        warning: Color(0xFFA17D41),
        success: Color(0xFF728C51),
        info: Color(0xFF708D65),
        codeBg: Color(0xFFE3DCD2),
        codeText: Color(0xFF54433A),
      ),
    ),
    ThemeVariant(
      id: 'lucent-orng',
      name: "Lucent Orng",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF000000),
        surface: Color(0xFF000000),
        surfaceStrong: Color(0xFF000000),
        border: Color(0xFFEC5B2B),
        borderStrong: Color(0xFFEE7948),
        text: Color(0xFFEEEEEE),
        muted: Color(0xFF808080),
        primary: Color(0xFFEC5B2B),
        accent: Color(0xFFFFF7F1),
        secondary: Color(0xFFEE7948),
        danger: Color(0xFFE06C75),
        warning: Color(0xFFEC5B2B),
        success: Color(0xFF6BA1E6),
        info: Color(0xFF56B6C2),
        codeBg: Color(0xFF000000),
        codeText: Color(0xFFEEEEEE),
      ),
    ),
    ThemeVariant(
      id: 'lucent-orng-light',
      name: "Lucent Orng (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFFFFFF),
        surface: Color(0xFFFFFFFF),
        surfaceStrong: Color(0xFFFFFFFF),
        border: Color(0xFFEC5B2B),
        borderStrong: Color(0xFFC94D24),
        text: Color(0xFF1A1A1A),
        muted: Color(0xFF8A8A8A),
        primary: Color(0xFFEC5B2B),
        accent: Color(0xFFC94D24),
        secondary: Color(0xFFEE7948),
        danger: Color(0xFFD1383D),
        warning: Color(0xFFEC5B2B),
        success: Color(0xFF0062D1),
        info: Color(0xFF318795),
        codeBg: Color(0xFFFFFFFF),
        codeText: Color(0xFF1A1A1A),
      ),
    ),
    ThemeVariant(
      id: 'material',
      name: "Material",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF263238),
        surface: Color(0xFF1E272C),
        surfaceStrong: Color(0xFF37474F),
        border: Color(0xFF37474F),
        borderStrong: Color(0xFF82AAFF),
        text: Color(0xFFEEFFFF),
        muted: Color(0xFF90A1A9),
        primary: Color(0xFF82AAFF),
        accent: Color(0xFF89DDFF),
        secondary: Color(0xFFC792EA),
        danger: Color(0xFFF07178),
        warning: Color(0xFFFFCB6B),
        success: Color(0xFFC3E88D),
        info: Color(0xFFFFCB6B),
        codeBg: Color(0xFF37474F),
        codeText: Color(0xFFEEFFFF),
      ),
    ),
    ThemeVariant(
      id: 'material-light',
      name: "Material (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFAFAFA),
        surface: Color(0xFFF5F5F5),
        surfaceStrong: Color(0xFFE7E7E8),
        border: Color(0xFFE0E0E0),
        borderStrong: Color(0xFF6182B8),
        text: Color(0xFF263238),
        muted: Color(0xFF65737A),
        primary: Color(0xFF6182B8),
        accent: Color(0xFF39ADB5),
        secondary: Color(0xFF7C4DFF),
        danger: Color(0xFFE53935),
        warning: Color(0xFFBF8600),
        success: Color(0xFF7B9C4C),
        info: Color(0xFFF4511E),
        codeBg: Color(0xFFE7E7E8),
        codeText: Color(0xFF263238),
      ),
    ),
    ThemeVariant(
      id: 'matrix',
      name: "Matrix",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF0A0E0A),
        surface: Color(0xFF0E130D),
        surfaceStrong: Color(0xFF141C12),
        border: Color(0xFF1E2A1B),
        borderStrong: Color(0xFF2EFF6A),
        text: Color(0xFF62FF94),
        muted: Color(0xFF8CA391),
        primary: Color(0xFF2EFF6A),
        accent: Color(0xFFC770FF),
        secondary: Color(0xFF00EFFF),
        danger: Color(0xFFFF4B4B),
        warning: Color(0xFFE6FF57),
        success: Color(0xFF62FF94),
        info: Color(0xFF30B3FF),
        codeBg: Color(0xFF141C12),
        codeText: Color(0xFF62FF94),
      ),
    ),
    ThemeVariant(
      id: 'matrix-light',
      name: "Matrix (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFEEF3EA),
        surface: Color(0xFFE4EBE1),
        surfaceStrong: Color(0xFFDAE1D7),
        border: Color(0xFF748476),
        borderStrong: Color(0xFF1CC24B),
        text: Color(0xFF203022),
        muted: Color(0xFF637064),
        primary: Color(0xFF169B3C),
        accent: Color(0xFFC770FF),
        secondary: Color(0xFF24F6D9),
        danger: Color(0xFFF24747),
        warning: Color(0xFF7F8C30),
        success: Color(0xFF169B3C),
        info: Color(0xFF268FCC),
        codeBg: Color(0xFFDAE1D7),
        codeText: Color(0xFF203022),
      ),
    ),
    ThemeVariant(
      id: 'mercury',
      name: "Mercury",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF171721),
        surface: Color(0xFF10101A),
        surfaceStrong: Color(0xFF272735),
        border: Color(0x1FB4B7C8),
        borderStrong: Color(0xFF8DA4F5),
        text: Color(0xFFDDDDE5),
        muted: Color(0xFF9D9DA8),
        primary: Color(0xFF8DA4F5),
        accent: Color(0xFF8DA4F5),
        secondary: Color(0xFFA7B6F8),
        danger: Color(0xFFFC92B4),
        warning: Color(0xFFFC9B6F),
        success: Color(0xFF77C599),
        info: Color(0xFF77BECF),
        codeBg: Color(0xFF272735),
        codeText: Color(0xFFDDDDE5),
      ),
    ),
    ThemeVariant(
      id: 'mercury-light',
      name: "Mercury (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFFFFFF),
        surface: Color(0xFFFBFCFD),
        surfaceStrong: Color(0xFFF4F5F9),
        border: Color(0x1A707393),
        borderStrong: Color(0xFF5266EB),
        text: Color(0xFF363644),
        muted: Color(0xFF70707D),
        primary: Color(0xFF5266EB),
        accent: Color(0xFF8DA4F5),
        secondary: Color(0xFF465BD1),
        danger: Color(0xFFB0175F),
        warning: Color(0xFFA44200),
        success: Color(0xFF036E43),
        info: Color(0xFF007F95),
        codeBg: Color(0xFFF4F5F9),
        codeText: Color(0xFF363644),
      ),
    ),
    ThemeVariant(
      id: 'monokai',
      name: "Monokai",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF272822),
        surface: Color(0xFF1E1F1C),
        surfaceStrong: Color(0xFF3E3D32),
        border: Color(0xFF3E3D32),
        borderStrong: Color(0xFF66D9EF),
        text: Color(0xFFF8F8F2),
        muted: Color(0xFF989586),
        primary: Color(0xFF66D9EF),
        accent: Color(0xFFA6E22E),
        secondary: Color(0xFFAE81FF),
        danger: Color(0xFFF92672),
        warning: Color(0xFFE6DB74),
        success: Color(0xFFA6E22E),
        info: Color(0xFFFD971F),
        codeBg: Color(0xFF3E3D32),
        codeText: Color(0xFFF8F8F2),
      ),
    ),
    ThemeVariant(
      id: 'monokai-light',
      name: "Monokai (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFAFAFA),
        surface: Color(0xFFF0F0F0),
        surfaceStrong: Color(0xFFE0E0E0),
        border: Color(0xFFD0D0D0),
        borderStrong: Color(0xFF66D9EF),
        text: Color(0xFF272822),
        muted: Color(0xFF75715E),
        primary: Color(0xFF4798A7),
        accent: Color(0xFFA6E22E),
        secondary: Color(0xFFAE81FF),
        danger: Color(0xFFF92672),
        warning: Color(0xFFCA7919),
        success: Color(0xFF749E20),
        info: Color(0xFFCA7919),
        codeBg: Color(0xFFE0E0E0),
        codeText: Color(0xFF272822),
      ),
    ),
    ThemeVariant(
      id: 'nightowl',
      name: "Night Owl",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF011627),
        surface: Color(0xFF0B253A),
        surfaceStrong: Color(0xFF0B253A),
        border: Color(0xFF5F7E97),
        borderStrong: Color(0xFF82AAFF),
        text: Color(0xFFD6DEEB),
        muted: Color(0xFF67849C),
        primary: Color(0xFF82AAFF),
        accent: Color(0xFFC792EA),
        secondary: Color(0xFF7FDBCA),
        danger: Color(0xFFEF5350),
        warning: Color(0xFFECC48D),
        success: Color(0xFFC5E478),
        info: Color(0xFF82AAFF),
        codeBg: Color(0xFF0B253A),
        codeText: Color(0xFFD6DEEB),
      ),
    ),
    ThemeVariant(
      id: 'nord',
      name: "Nord",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF2E3440),
        surface: Color(0xFF3B4252),
        surfaceStrong: Color(0xFF434C5E),
        border: Color(0xFF434C5E),
        borderStrong: Color(0xFF4C566A),
        text: Color(0xFFECEFF4),
        muted: Color(0xFF97A0B0),
        primary: Color(0xFF88C0D0),
        accent: Color(0xFF8FBCBB),
        secondary: Color(0xFF81A1C1),
        danger: Color(0xFFBF616A),
        warning: Color(0xFFD08770),
        success: Color(0xFFA3BE8C),
        info: Color(0xFF88C0D0),
        codeBg: Color(0xFF434C5E),
        codeText: Color(0xFFD8DEE9),
      ),
    ),
    ThemeVariant(
      id: 'nord-light',
      name: "Nord (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFECEFF4),
        surface: Color(0xFFE5E9F0),
        surfaceStrong: Color(0xFFD8DEE9),
        border: Color(0xFF4C566A),
        borderStrong: Color(0xFF434C5E),
        text: Color(0xFF2E3440),
        muted: Color(0xFF3B4252),
        primary: Color(0xFF5E81AC),
        accent: Color(0xFF8FBCBB),
        secondary: Color(0xFF81A1C1),
        danger: Color(0xFFBF616A),
        warning: Color(0xFFB1735F),
        success: Color(0xFF7A8F69),
        info: Color(0xFF5E81AC),
        codeBg: Color(0xFFD8DEE9),
        codeText: Color(0xFF2E3440),
      ),
    ),
    ThemeVariant(
      id: 'one-dark',
      name: "One Dark",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF282C34),
        surface: Color(0xFF21252B),
        surfaceStrong: Color(0xFF353B45),
        border: Color(0xFF393F4A),
        borderStrong: Color(0xFF61AFEF),
        text: Color(0xFFABB2BF),
        muted: Color(0xFF959AA2),
        primary: Color(0xFF61AFEF),
        accent: Color(0xFF56B6C2),
        secondary: Color(0xFFC678DD),
        danger: Color(0xFFE06C75),
        warning: Color(0xFFE5C07B),
        success: Color(0xFF98C379),
        info: Color(0xFFD19A66),
        codeBg: Color(0xFF353B45),
        codeText: Color(0xFFABB2BF),
      ),
    ),
    ThemeVariant(
      id: 'one-dark-light',
      name: "One Dark (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFAFAFA),
        surface: Color(0xFFF0F0F1),
        surfaceStrong: Color(0xFFEAEAEB),
        border: Color(0xFFD1D1D2),
        borderStrong: Color(0xFF4078F2),
        text: Color(0xFF383A42),
        muted: Color(0xFF707175),
        primary: Color(0xFF4078F2),
        accent: Color(0xFF0184BC),
        secondary: Color(0xFFA626A4),
        danger: Color(0xFFE45649),
        warning: Color(0xFFC18401),
        success: Color(0xFF50A14F),
        info: Color(0xFF986801),
        codeBg: Color(0xFFEAEAEB),
        codeText: Color(0xFF383A42),
      ),
    ),
    ThemeVariant(
      id: 'opencode',
      name: "OpenCode",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF09090B),
        surface: Color(0xFF121215),
        surfaceStrong: Color(0xFF18181C),
        border: Color(0xFF3F3F46),
        borderStrong: Color(0xFF71717A),
        text: Color(0xFFF4F4F5),
        muted: Color(0xFFA1A1AA),
        primary: Color(0xFF6366F1),
        accent: Color(0xFF9D7CD8),
        secondary: Color(0xFF5C9CF5),
        danger: Color(0xFFE06C75),
        warning: Color(0xFFF5A742),
        success: Color(0xFF7FD88F),
        info: Color(0xFF56B6C2),
        codeBg: Color(0xFF18181C),
        codeText: Color(0xFFF4F4F5),
      ),
    ),
    ThemeVariant(
      id: 'opencode-light',
      name: "OpenCode (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFFFFFF),
        surface: Color(0xFFFAFAFA),
        surfaceStrong: Color(0xFFF5F5F5),
        border: Color(0xFFB8B8B8),
        borderStrong: Color(0xFFA0A0A0),
        text: Color(0xFF1A1A1A),
        muted: Color(0xFF757575),
        primary: Color(0xFF3B7DD8),
        accent: Color(0xFFD68C27),
        secondary: Color(0xFF7B5BB6),
        danger: Color(0xFFD1383D),
        warning: Color(0xFFCB8525),
        success: Color(0xFF3D9A57),
        info: Color(0xFF318795),
        codeBg: Color(0xFFF5F5F5),
        codeText: Color(0xFF1A1A1A),
      ),
    ),
    ThemeVariant(
      id: 'orng',
      name: "Orng",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF0A0A0A),
        surface: Color(0xFF141414),
        surfaceStrong: Color(0xFF1E1E1E),
        border: Color(0xFFEC5B2B),
        borderStrong: Color(0xFFEE7948),
        text: Color(0xFFEEEEEE),
        muted: Color(0xFF808080),
        primary: Color(0xFFEC5B2B),
        accent: Color(0xFFFFF7F1),
        secondary: Color(0xFFEE7948),
        danger: Color(0xFFE06C75),
        warning: Color(0xFFEC5B2B),
        success: Color(0xFF6BA1E6),
        info: Color(0xFF56B6C2),
        codeBg: Color(0xFF1E1E1E),
        codeText: Color(0xFFEEEEEE),
      ),
    ),
    ThemeVariant(
      id: 'orng-light',
      name: "Orng (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFFFFFF),
        surface: Color(0xFFFFF7F1),
        surfaceStrong: Color(0xFFF5F0EB),
        border: Color(0xFFEC5B2B),
        borderStrong: Color(0xFFC94D24),
        text: Color(0xFF1A1A1A),
        muted: Color(0xFF757575),
        primary: Color(0xFFEC5B2B),
        accent: Color(0xFFC94D24),
        secondary: Color(0xFFEE7948),
        danger: Color(0xFFD1383D),
        warning: Color(0xFFEC5B2B),
        success: Color(0xFF0062D1),
        info: Color(0xFF318795),
        codeBg: Color(0xFFF5F0EB),
        codeText: Color(0xFF1A1A1A),
      ),
    ),
    ThemeVariant(
      id: 'osaka-jade',
      name: "Osaka Jade",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF111C18),
        surface: Color(0xFF1A2520),
        surfaceStrong: Color(0xFF23372B),
        border: Color(0xFF3D4A44),
        borderStrong: Color(0xFF2DD5B7),
        text: Color(0xFFC1C497),
        muted: Color(0xFF75867C),
        primary: Color(0xFF2DD5B7),
        accent: Color(0xFF549E6A),
        secondary: Color(0xFFD2689C),
        danger: Color(0xFFFF5345),
        warning: Color(0xFFE5C736),
        success: Color(0xFF549E6A),
        info: Color(0xFF2DD5B7),
        codeBg: Color(0xFF23372B),
        codeText: Color(0xFFC1C497),
      ),
    ),
    ThemeVariant(
      id: 'osaka-jade-light',
      name: "Osaka Jade (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFF6F5DD),
        surface: Color(0xFFE8E7CC),
        surfaceStrong: Color(0xFFD5D4B8),
        border: Color(0xFFA8A78C),
        borderStrong: Color(0xFF1FAA90),
        text: Color(0xFF111C18),
        muted: Color(0xFF53685B),
        primary: Color(0xFF1C9982),
        accent: Color(0xFF3D7A52),
        secondary: Color(0xFFA8527A),
        danger: Color(0xFFC7392D),
        warning: Color(0xFF9A881B),
        success: Color(0xFF3D7A52),
        info: Color(0xFF1C9982),
        codeBg: Color(0xFFD5D4B8),
        codeText: Color(0xFF111C18),
      ),
    ),
    ThemeVariant(
      id: 'palenight',
      name: "Palenight",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF292D3E),
        surface: Color(0xFF1E2132),
        surfaceStrong: Color(0xFF32364A),
        border: Color(0xFF32364A),
        borderStrong: Color(0xFF82AAFF),
        text: Color(0xFFA6ACCD),
        muted: Color(0xFF959AB5),
        primary: Color(0xFF82AAFF),
        accent: Color(0xFF89DDFF),
        secondary: Color(0xFFC792EA),
        danger: Color(0xFFF07178),
        warning: Color(0xFFFFCB6B),
        success: Color(0xFFC3E88D),
        info: Color(0xFFF78C6C),
        codeBg: Color(0xFF32364A),
        codeText: Color(0xFFA6ACCD),
      ),
    ),
    ThemeVariant(
      id: 'palenight-light',
      name: "Palenight (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFAFAFA),
        surface: Color(0xFFF5F5F5),
        surfaceStrong: Color(0xFFE7E7E8),
        border: Color(0xFFE0E0E0),
        borderStrong: Color(0xFF4976EB),
        text: Color(0xFF292D3E),
        muted: Color(0xFF657184),
        primary: Color(0xFF4976EB),
        accent: Color(0xFF00ACC1),
        secondary: Color(0xFFA854F2),
        danger: Color(0xFFE53935),
        warning: Color(0xFFBF8600),
        success: Color(0xFF7B9C4C),
        info: Color(0xFFF4511E),
        codeBg: Color(0xFFE7E7E8),
        codeText: Color(0xFF292D3E),
      ),
    ),
    ThemeVariant(
      id: 'rosepine',
      name: "Rosé Pine",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF191724),
        surface: Color(0xFF1F1D2E),
        surfaceStrong: Color(0xFF26233A),
        border: Color(0xFF403D52),
        borderStrong: Color(0xFF9CCFD8),
        text: Color(0xFFE0DEF4),
        muted: Color(0xFF848098),
        primary: Color(0xFF9CCFD8),
        accent: Color(0xFFEBBCBA),
        secondary: Color(0xFFC4A7E7),
        danger: Color(0xFFEB6F92),
        warning: Color(0xFFF6C177),
        success: Color(0xFF31748F),
        info: Color(0xFF9CCFD8),
        codeBg: Color(0xFF26233A),
        codeText: Color(0xFF908CAA),
      ),
    ),
    ThemeVariant(
      id: 'rosepine-light',
      name: "Rosé Pine (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFAF4ED),
        surface: Color(0xFFFFFAF3),
        surfaceStrong: Color(0xFFF2E9E1),
        border: Color(0xFFDFDAD9),
        borderStrong: Color(0xFF31748F),
        text: Color(0xFF575279),
        muted: Color(0xFF726E7C),
        primary: Color(0xFF31748F),
        accent: Color(0xFFD7827E),
        secondary: Color(0xFF907AA9),
        danger: Color(0xFFB4637A),
        warning: Color(0xFFBB7E2A),
        success: Color(0xFF286983),
        info: Color(0xFF56949F),
        codeBg: Color(0xFFF2E9E1),
        codeText: Color(0xFF67637D),
      ),
    ),
    ThemeVariant(
      id: 'solarized',
      name: "Solarized",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF002B36),
        surface: Color(0xFF073642),
        surfaceStrong: Color(0xFF073642),
        border: Color(0xFF073642),
        borderStrong: Color(0xFF586E75),
        text: Color(0xFF8F9FA1),
        muted: Color(0xFF829298),
        primary: Color(0xFF268BD2),
        accent: Color(0xFF2AA198),
        secondary: Color(0xFF6C71C4),
        danger: Color(0xFFDC322F),
        warning: Color(0xFFB58900),
        success: Color(0xFF859900),
        info: Color(0xFFCB4B16),
        codeBg: Color(0xFF073642),
        codeText: Color(0xFF8F9FA1),
      ),
    ),
    ThemeVariant(
      id: 'solarized-light',
      name: "Solarized (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFDF6E3),
        surface: Color(0xFFEEE8D5),
        surfaceStrong: Color(0xFFEEE8D5),
        border: Color(0xFFEEE8D5),
        borderStrong: Color(0xFF93A1A1),
        text: Color(0xFF56696F),
        muted: Color(0xFF677171),
        primary: Color(0xFF268BD2),
        accent: Color(0xFF2AA198),
        secondary: Color(0xFF6C71C4),
        danger: Color(0xFFDC322F),
        warning: Color(0xFFAC8200),
        success: Color(0xFF7E9100),
        info: Color(0xFFCB4B16),
        codeBg: Color(0xFFEEE8D5),
        codeText: Color(0xFF56696F),
      ),
    ),
    ThemeVariant(
      id: 'synthwave84',
      name: "Synthwave '84",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF262335),
        surface: Color(0xFF1E1A29),
        surfaceStrong: Color(0xFF2A2139),
        border: Color(0xFF495495),
        borderStrong: Color(0xFF36F9F6),
        text: Color(0xFFFFFFFF),
        muted: Color(0xFF848BBD),
        primary: Color(0xFF36F9F6),
        accent: Color(0xFFB084EB),
        secondary: Color(0xFFFF7EDB),
        danger: Color(0xFFFE4450),
        warning: Color(0xFFFEDE5D),
        success: Color(0xFF72F1B8),
        info: Color(0xFFFF8B39),
        codeBg: Color(0xFF2A2139),
        codeText: Color(0xFFFFFFFF),
      ),
    ),
    ThemeVariant(
      id: 'synthwave84-light',
      name: "Synthwave '84 (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFAFAFA),
        surface: Color(0xFFF5F5F5),
        surfaceStrong: Color(0xFFEEEEEE),
        border: Color(0xFFE0E0E0),
        borderStrong: Color(0xFF00BCD4),
        text: Color(0xFF262335),
        muted: Color(0xFF5C5C8A),
        primary: Color(0xFF00A0B4),
        accent: Color(0xFF9C27B0),
        secondary: Color(0xFFE91E63),
        danger: Color(0xFFF44336),
        warning: Color(0xFFCC7A00),
        success: Color(0xFF449E48),
        info: Color(0xFFFF5722),
        codeBg: Color(0xFFEEEEEE),
        codeText: Color(0xFF262335),
      ),
    ),
    ThemeVariant(
      id: 'tokyonight',
      name: "Tokyo Night",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF1A1B26),
        surface: Color(0xFF1E2030),
        surfaceStrong: Color(0xFF222436),
        border: Color(0xFF737AA2),
        borderStrong: Color(0xFF9099B2),
        text: Color(0xFFC8D3F5),
        muted: Color(0xFF828BB8),
        primary: Color(0xFF82AAFF),
        accent: Color(0xFFFF966C),
        secondary: Color(0xFFC099FF),
        danger: Color(0xFFFF757F),
        warning: Color(0xFFFF966C),
        success: Color(0xFFC3E88D),
        info: Color(0xFF82AAFF),
        codeBg: Color(0xFF222436),
        codeText: Color(0xFFC8D3F5),
      ),
    ),
    ThemeVariant(
      id: 'tokyonight-light',
      name: "Tokyo Night (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFE1E2E7),
        surface: Color(0xFFD5D6DB),
        surfaceStrong: Color(0xFFC8C9CE),
        border: Color(0xFF737A8C),
        borderStrong: Color(0xFF5A607D),
        text: Color(0xFF2C4D99),
        muted: Color(0xFF606572),
        primary: Color(0xFF2E7DE9),
        accent: Color(0xFFB15C00),
        secondary: Color(0xFF9854F1),
        danger: Color(0xFFF52A65),
        warning: Color(0xFFB15C00),
        success: Color(0xFF587539),
        info: Color(0xFF2E7DE9),
        codeBg: Color(0xFFC8C9CE),
        codeText: Color(0xFF2C4D99),
      ),
    ),
    ThemeVariant(
      id: 'vercel',
      name: "Vercel",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF000000),
        surface: Color(0xFF1A1A1A),
        surfaceStrong: Color(0xFF292929),
        border: Color(0xFF1F1F1F),
        borderStrong: Color(0xFF454545),
        text: Color(0xFFEDEDED),
        muted: Color(0xFF878787),
        primary: Color(0xFF0070F3),
        accent: Color(0xFF8E4EC6),
        secondary: Color(0xFF52A8FF),
        danger: Color(0xFFE5484D),
        warning: Color(0xFFFFB224),
        success: Color(0xFF46A758),
        info: Color(0xFF52A8FF),
        codeBg: Color(0xFF292929),
        codeText: Color(0xFFEDEDED),
      ),
    ),
    ThemeVariant(
      id: 'vercel-light',
      name: "Vercel (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFFFFFF),
        surface: Color(0xFFFAFAFA),
        surfaceStrong: Color(0xFFEAEAEA),
        border: Color(0xFFEAEAEA),
        borderStrong: Color(0xFF999999),
        text: Color(0xFF171717),
        muted: Color(0xFF666666),
        primary: Color(0xFF0070F3),
        accent: Color(0xFF8E4EC6),
        secondary: Color(0xFF0062D1),
        danger: Color(0xFFDC3545),
        warning: Color(0xFFD97F00),
        success: Color(0xFF388E3C),
        info: Color(0xFF0070F3),
        codeBg: Color(0xFFEAEAEA),
        codeText: Color(0xFF171717),
      ),
    ),
    ThemeVariant(
      id: 'vesper',
      name: "Vesper",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF101010),
        surface: Color(0xFF101010),
        surfaceStrong: Color(0xFF101010),
        border: Color(0xFF282828),
        borderStrong: Color(0xFFFFC799),
        text: Color(0xFFFFFFFF),
        muted: Color(0xFFA0A0A0),
        primary: Color(0xFFFFC799),
        accent: Color(0xFFFFC799),
        secondary: Color(0xFF99FFE4),
        danger: Color(0xFFFF8080),
        warning: Color(0xFFFFC799),
        success: Color(0xFF99FFE4),
        info: Color(0xFFFFC799),
        codeBg: Color(0xFF101010),
        codeText: Color(0xFFFFFFFF),
      ),
    ),
    ThemeVariant(
      id: 'vesper-light',
      name: "Vesper (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFFFFFF),
        surface: Color(0xFFF0F0F0),
        surfaceStrong: Color(0xFFE0E0E0),
        border: Color(0xFFD0D0D0),
        borderStrong: Color(0xFFFFC799),
        text: Color(0xFF101010),
        muted: Color(0xFF707070),
        primary: Color(0xFFB38B6B),
        accent: Color(0xFFFFC799),
        secondary: Color(0xFF99FFE4),
        danger: Color(0xFFD96D6D),
        warning: Color(0xFFB38B6B),
        success: Color(0xFF5C9989),
        info: Color(0xFFB38B6B),
        codeBg: Color(0xFFE0E0E0),
        codeText: Color(0xFF101010),
      ),
    ),
    ThemeVariant(
      id: 'zenburn',
      name: "Zenburn",
      kind: ThemeVariantKind.dark,
      colors: ThemeVariantColors(
        bg: Color(0xFF3F3F3F),
        surface: Color(0xFF4F4F4F),
        surfaceStrong: Color(0xFF5F5F5F),
        border: Color(0xFF5F5F5F),
        borderStrong: Color(0xFF8CD0D3),
        text: Color(0xFFDCDCCC),
        muted: Color(0xFFADADAD),
        primary: Color(0xFF8CD0D3),
        accent: Color(0xFF93E0E3),
        secondary: Color(0xFFDC8CC3),
        danger: Color(0xFFCC9393),
        warning: Color(0xFFF0DFAF),
        success: Color(0xFF7F9F7F),
        info: Color(0xFFDFAF8F),
        codeBg: Color(0xFF5F5F5F),
        codeText: Color(0xFFDCDCCC),
      ),
    ),
    ThemeVariant(
      id: 'zenburn-light',
      name: "Zenburn (claro)",
      kind: ThemeVariantKind.light,
      colors: ThemeVariantColors(
        bg: Color(0xFFFFFFEF),
        surface: Color(0xFFF5F5E5),
        surfaceStrong: Color(0xFFEBEBDB),
        border: Color(0xFFD0D0C0),
        borderStrong: Color(0xFF5F7F8F),
        text: Color(0xFF3F3F3F),
        muted: Color(0xFF6F6F6F),
        primary: Color(0xFF5F7F8F),
        accent: Color(0xFF5F8F8F),
        secondary: Color(0xFF8F5F8F),
        danger: Color(0xFF8F5F5F),
        warning: Color(0xFF8F8F5F),
        success: Color(0xFF5F8F5F),
        info: Color(0xFF8F7F5F),
        codeBg: Color(0xFFEBEBDB),
        codeText: Color(0xFF3F3F3F),
      ),
    ),
  ];

  /// Busca en el catálogo por id (`null` si no existe o si no hay id, que es
  /// lo que guarda la pref cuando el usuario dejó el tema en Automático).
  static ThemeVariant? byId(String? id) {
    if (id == null || id.isEmpty) return null;
    for (final variant in builtIn) {
      if (variant.id == id) return variant;
    }
    return null;
  }

  /// Variantes de un tipo, en el orden del catálogo (secciones Claro/Oscuro
  /// del selector).
  static List<ThemeVariant> ofKind(ThemeVariantKind kind) =>
      builtIn.where((variant) => variant.kind == kind).toList();
}
